FROM python:3.12-slim

# install uv
COPY --from=ghcr.io/astral-sh/uv:0.9.11 /uv /uvx /bin/

WORKDIR /app
COPY pyproject.toml uv.lock ./

# sync dependencies
RUN uv sync --dev

# copy source
COPY . .

EXPOSE 8000
CMD ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
